#!/bin/bash
# Kills the sleep in dwm_bar.sh to refresh the bar
# Modified version of Luke Smith's refbar.sh script

kill "$(pstree -lp | grep -- -statusbar\([0-9] | sed "s/.*sleep(\([0-9]\+\))/\1/")"
