#!/bin/bash
# Opens a new terminal and runs the command.

usage() {
    printf "Usage: shell_wrapper [COMMAND]
Opens a new terminal and runs the command."
}

[ $# -eq 0 ] && usage && exit 1
st -e bash -c "$1;exec bash"
